import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Product } from '../models/product.model';

@Injectable({ providedIn: 'root' })
export class ProductService {
  private readonly products: Product[] = [
    {
      id: 1,
      name: 'Coleção Entretampos: Lavanda',
      category: 'vela',
      fragrance: 'Floral, Fresca, Adocicada, Herbal',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 31.90,
      imagePlaceholder: 'assets/Candle-Lavanda.jpeg',
      weightG: 90,
    },
    {
      id: 2,
      name: 'Coleção Entretampos: Pistache',
      category: 'vela',
      fragrance: 'Cremosidade, Baunilha, Gourmand Oriental',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 31.90,
      imagePlaceholder: 'assets/Candle-Pistache.jpeg',
      weightG: 90,
    },
    {
      id: 3,
      name: 'Coleção Entretampos: Chá Branco',
      category: 'vela',
      fragrance: 'Fresco, Elegante, Jasmin, Flor de Lótus',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 31.90,
      imagePlaceholder: 'assets/Candle-Cha-Branco.jpeg',
      weightG: 90,
    },
    {
      id: 4,
      name: 'Coleção Sugar Berry: Copo Vidro Quadrado',
      category: 'vela',
      fragrance: 'Morango, Doce, Fruta',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 46.90,
      imagePlaceholder: 'assets/Candle-StrawBerry-1.jpeg',
      weightG: 100,
    },
    {
      id: 5,
      name: 'Coleção Sugar Berry: Pote Patê',
      category: 'vela',
      fragrance: 'Morango, Doce, Fruta',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 36.90,
      imagePlaceholder: 'assets/Candle-StrawBerry-2.jpeg',
      weightG: 100,
    },
    {
      id: 6,
      name: 'Coleção Sugar Berry: Imponente na Taça (18cm)',
      category: 'vela',
      fragrance: 'Morango, Doce, Fruta',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 69.90,
      imagePlaceholder: 'assets/Candle-StrawBerry-3.jpeg',
      weightG: 300,
    },
    {
      id: 7,
      name: 'Coleção Sugar Berry: Flor de Cerejeira',
      category: 'vela',
      fragrance: 'Cereja',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 35.90,
      imagePlaceholder: 'assets/Candle-Flower-Cer.jpeg',
      weightG: 80,
    },
    {
      id: 8,
      name: 'Coleção Sugar Berry: Lavanda',
      category: 'vela',
      fragrance: 'Floral, Fresca, Adocicada, Herbal',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 35.90,
      imagePlaceholder: 'assets/Candle-Lavanda-2.jpeg',
      weightG: 80,
    },
    {
      id: 9,
      name: 'Coleção Sugar Berry: Olho Grego',
      category: 'vela',
      fragrance: 'Proteção, Energia, Peônia, Pavio de Madeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 46.90,
      imagePlaceholder: 'assets/Candle-Evil-Eye.jpeg',
      weightG: 80,
    },
    {
      id: 10,
      name: 'Coleção Gourmet: Café (Caneca Esmalta)',
      category: 'vela',
      fragrance: 'Café, Doce',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 41.50,
      imagePlaceholder: 'assets/Candle-Coffee.jpeg',
      weightG: 200,
    },
    {
      id: 11,
      name: 'Coleção Gourmet: Chocolate Belga',
      category: 'vela',
      fragrance: 'Chocolate, Doce, Coco',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 59.90,
      imagePlaceholder: 'assets/Candle-Chocolat.jpeg',
      weightG: 200,
    },
    {
      id: 12,
      name: 'Coleção Gourmet: Chocolate Belga (Taça de Vidro)',
      category: 'vela',
      fragrance: 'Chocolate, Doce, Coco, Café Expresso',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 49.90,
      imagePlaceholder: 'assets/Candle-Chocolat-2.jpeg',
      weightG: 100,
    },
    {
      id: 13,
      name: 'Coleção Fé: Luminária Nossa Senhora Aparecida (Reutilizável)',
      category: 'vela',
      fragrance: 'Sweet Floral',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 69.80,
      imagePlaceholder: 'assets/Candle-Fe.jpeg',
      weightG: 100,
    },
    {
      id: 14,
      name: 'Coleção Fé: Nossa Senhora Aparecida / Nossa Senhora Perpétuo Socorro',
      category: 'vela',
      fragrance: 'Lavanda, Calmaria',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 39.90,
      imagePlaceholder: 'assets/Candle-NSA-NSPC.jpeg',
      weightG: 100,
    },
    {
      id: 15,
      name: 'Kit Difusor Aromático: Morango (Consulte Cor da Cerâmica)',
      category: 'difusor',
      fragrance: 'Doce, Vibrante',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 62.90,
      imagePlaceholder: 'assets/Dif.jpeg',
      volumML: 10,
    },
    {
      id: 16,
      name: 'Kit Difusor Aromático: Jasmin (Consulte Cor da Cerâmica',
      category: 'difusor',
      fragrance: 'Floral, Sofisticação',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 62.90,
      imagePlaceholder: 'assets/Dif.jpeg',
      volumML: 10,
    },
    {
      id: 17,
      name: 'Kit Difusor Aromático: Chá Branco (Consulte Cor da Cerâmica',
      category: 'difusor',
      fragrance: 'Leveza, Elegância',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 62.90,
      imagePlaceholder: 'assets/Dif.jpeg',
      volumML: 10,
    },
    {
      id: 18,
      name: 'Aromatizador Veicular em Vidro (Tampa de Madeira)',
      category: 'difusor',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 15.00,
      imagePlaceholder: 'assets/Dif-Car.jpeg',
      volumML: 8,
    },
    {
      id: 19,
      name: 'Coleção Difusores e Home-Sprays (Embalagem Vidro e Pet): Difusor Vidro',
      category: 'difusor',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 42.90,
      imagePlaceholder: 'assets/Dif-Kit.jpeg',
      volumML: 250,
    },
    {
      id: 20,
      name: 'Coleção Difusores e Home-Sprays (Embalagem Vidro e Pet): Difusor Pet',
      category: 'difusor',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 37.90,
      imagePlaceholder: 'assets/Dif-Kit.jpeg',
      volumML: 250,
    },
    {
      id: 21,
      name: 'Coleção Difusores e Home-Sprays (Embalagem Vidro e Pet): Difusor Vidro',
      category: 'difusor',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 25.00,
      imagePlaceholder: 'assets/Dif-Kit.jpeg',
      volumML: 30,
    },
    {
      id: 21,
      name: 'Coleção Difusores e Home-Sprays (Embalagem Vidro e Pet): Difusor Vidro Para Cômodos',
      category: 'difusor',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 20.00,
      imagePlaceholder: 'assets/Dif-Kit.jpeg',
      volumML: 25,
    },
    {
      id: 22,
      name: 'Coleção Difusores e Home-Sprays (Embalagem Vidro e Pet): Home-Spray Vidro - Bico do Spray',
      category: 'home-spray',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 35.90,
      imagePlaceholder: 'assets/Dif-Kit.jpeg',
      volumML: 150,
    },
    {
      id: 22,
      name: 'Coleção Difusores e Home-Sprays (Embalagem Vidro e Pet): Home-Spray Vidro - Bico do Gatilho',
      category: 'home-spray',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 39.90,
      imagePlaceholder: 'assets/Dif-Kit.jpeg',
      volumML: 150,
    },
    {
      id: 23,
      name: 'Coleção Difusores e Home-Sprays (Embalagem Vidro e Pet): Home-Spray Pet - Bico do Spray',
      category: 'home-spray',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 41.90,
      imagePlaceholder: 'assets/Dif-Kit.jpeg',
      volumML: 300,
    },
    {
      id: 24,
      name: 'Coleção Difusores e Home-Sprays (Embalagem Vidro e Pet): Home-Spray Pet',
      category: 'home-spray',
      fragrance: 'Bambu, Flor de Cerejeira',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 35.00,
      imagePlaceholder: 'assets/Dif-Kit.jpeg',
      volumML: 250,
    },
    {
      id: 25,
      name: 'Vela para Massagem: Alecrim e Chá Branco',
      category: 'vela',
      fragrance: 'Frescor, Leveza',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 59.90,
      imagePlaceholder: 'assets/Candle-Massage.jpeg',
      weightG: 250,
    },
    {
      id: 26,
      name: 'Vela para Massagem: Flor de Figo',
      category: 'vela',
      fragrance: 'Sofisticação',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 59.90,
      imagePlaceholder: 'assets/Candle-Massage.jpeg',
      weightG: 10,
    },
    {
      id: 27,
      name: 'Vela para Massagem: Baunilha',
      category: 'vela',
      fragrance: 'Aconchego, Doce',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 59.90,
      imagePlaceholder: 'assets/Candle-Massage.jpeg',
      weightG: 10,
    },
    {
      id: 28,
      name: 'Coleção Lembranças e Eventos: Chá Revelação',
      category: 'vela',
      fragrance: 'Comfort Baby',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 51.90,
      imagePlaceholder: 'assets/Candle-Baby.jpeg',
      weightG: 200,
    },
    {
      id: 29,
      name: 'Coleção Lembranças e Eventos: Cerveja (Copo Americano e Rótulo Personalizável) - Consulte Valores',
      category: 'vela',
      fragrance: 'Cera de Coco',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 20.00,
      imagePlaceholder: 'assets/Candle-Beer.jpeg',
      weightG: 150,
    },
    {
      id: 30,
      name: 'Coleção Lembranças e Eventos: Trio de Velas (Vidro Patê com Fósforos) - Rótulo, Fita e Aroma Ajustados ao Tema de Sua Festa, Valor Negociável',
      category: 'vela',
      fragrance: 'Escolha do Cliente',
      description: 'Feito com carinho, não em escala. Por serem artesanais, alguns produtos podem levar até 3 dias úteis para produção, além do prazo de entrega.',
      price: 45.00,
      imagePlaceholder: 'assets/Candle-Three.jpeg',
      weightG: 90,
    }
  ];

  getAll(): Observable<Product[]> {
    return of(this.products);
  }

  getById(id: number): Observable<Product | undefined> {
    return of(this.products.find((product) => product.id === id));
  }
}
