spring.application.name=candleshop
server.port=8081
cors.allowed-origin=http://localhost:4200
mercadopago.access-token=${MERCADO_PAGO_ACCESS_TOKEN}
mercadopago.webhook-secret=${MERCADO_PAGO_WEBHOOK_SECRET}